services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - DOMAIN=example.com                  # 修改为你的根域名
    restart: always

  quay:
    image: "registry:2.8.3"
    container_name: "quay"
    restart: "always"
    volumes:
      - "./quay/config.yml:/etc/docker/registry/config.yml"

  ghcr:
    image: "registry:2.8.3"
    container_name: "ghcr"
    restart: "always"
    volumes:
      - "./ghcr/config.yml:/etc/docker/registry/config.yml"

  gcr:
    image: "registry:2.8.3"
    container_name: "gcr"
    restart: "always"
    volumes:
      - "./gcr/config.yml:/etc/docker/registry/config.yml"

  docker:
    image: "registry:2.8.3"
    container_name: "docker"
    restart: "always"
    volumes:
      - "./docker/config.yml:/etc/docker/registry/config.yml"

  k8s:
    image: "registry:2.8.3"
    container_name: "k8s"
    restart: "always"
    volumes:
      - "./k8s/config.yml:/etc/docker/registry/config.yml"

  ghproxy:
    build:
      context: ./ghproxy
    container_name: "ghproxy"
    volumes:
      - ./ghproxy/public:/root/public   # 前端页面
    restart: "always"