services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - DOMAIN=example.com                  # 修改为你的根域名
    restart: always

  ghcr:
    image: "registry:2.8.3"
    container_name: "ghcr"
    restart: "always"
    volumes:
      - "./ghcr/config.yml:/etc/docker/registry/config.yml"

  docker:
    image: "registry:2.8.3"
    container_name: "docker"
    restart: "always"
    volumes:
      - "./docker/config.yml:/etc/docker/registry/config.yml"

  ghproxy:
    image: "ghcr.io/sky22333/hubproxy"
    container_name: "ghproxy"
    restart: "always"